### ISSUE TITLE
是否考虑支持springboot

### ISSUE THREAD

**Issue by ityouknow** [killme2008/xmemcached#51]
spring boot 这种开发理念越来越受到欢迎，基本很少的配置就可以使用各种组合，是否也会考虑支持。

**Comment by killme2008** [comment]
spring boot 只是个框架， xmc 是个类库，怎么样都能集成。不准备再提供任何第三方框架的 helper 了。

**Comment by killme2008** [comment]
可以自行参考

https://github.com/bmatthews68/memcached-spring-boot-starter

**Comment by ityouknow** [comment]
ok

**Comment by foreveryang321** [comment]
https://github.com/foreveryang321/xmemcached-spring-boot-starter

> application.yml
```yaml
spring:
  xmemcached:
    address: locahost:12200
    command-factory: binary
    session-locator: ketam
    socket-options:
      tcp-no-delay: true
      keep-alive: true
```

> 特性
- 支持原生xmemcached的绝大部分的配置
- 支持spring-cache，并通过自定义注解（@Expired），支持过期时间配置
```java
@Cacheable(cacheNames = "getName", key = "#p0", unless = "#result eq null")
@Expired(90)
public String getName(String name) {
    return name;
}
```
...
